# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gerves Francois BANIAKINA
email: gbaniakina2006@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Welcome to Gerves's Tech Hub!

Embark on an exciting journey into the world of software development, artificial intelligence, and full-stack engineering. As a recent graduate passionate about technology and innovation, I am eager to share my experiences in coding, AI, and machine learning.
Here, you will find insights, tutorials, and best practices for building robust and scalable applications using cutting-edge technologies.

Explore the dynamic intersection of front-end innovations and back-end architectures, and discover how I bring ideas to life with impactful digital solutions. Dive into my projects, explore the latest industry trends, and connect with me to advance technology.
Whether you're a fellow developer, an entrepreneur with a tech vision, or someone keen to learn, you'll find valuable resources here. Let's shape the future together by coding and harnessing the transformative power of AI and machine learning!

As I seek entry-level opportunities, I invite you to join me on this journey of discovery and growth in the tech world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gbaniaki.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
linkedin_uername: gbaniakina2006
github_username: GBANIAKI
search: true


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
